services:
  thread-db:
    image: mysql
    restart: always
    ports:
      - "3311:3306"
    volumes:
      - thread-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  interaction-db:
    image: mysql
    restart: always
    ports:
      - "3312:3306"
    volumes:
      - interaction-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  user-mongo:
    image: mongo
    restart: always
    ports:
      - "27777:27017"
    volumes:
      - user-mongo:/data/db

  thread-service:
    depends_on:
      thread-db:
        condition: service_started
    image: mrtnmrx/thread-service
    ports:
      - "8081:8081"
    links:
      - thread-db
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: password
      MYSQL_DB_URL: thread-db:3306
      INTERACTION_SERVICE_BASEURL: interaction-service:8082
      USER_SERVICE_BASEURL: user-service:8083
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  interaction-service:
    depends_on:
      interaction-db:
        condition: service_started
    image: mrtnmrx/interaction-service
    ports:
      - "8082:8082"
    links:
      - interaction-db
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: password
      MYSQL_DB_URL: interaction-db:3306
      USER_SERVICE_BASEURL: user-service:8083
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  user-service:
    depends_on:
      user-mongo:
        condition: service_started
    image: mrtnmrx/user-service
    ports:
      - "8083:8083"
    links:
      - user-mongo
    environment:
      MONGODB_URL: user-mongo:27017
      THREAD_SERVICE_BASEURL: thread-service:8081
      INTERACTION_SERVICE_BASEURL: interaction-service:8082
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  gateway:
    depends_on:
      - thread-service
      - interaction-service
      - user-service
    image: mrtnmrx/gateway
    ports:
      - "8084:8084"
    links:
      - thread-service
      - interaction-service
      - user-service
    environment:
      THREAD_SERVICE_BASEURL: thread-service:8081
      INTERACTION_SERVICE_BASEURL: interaction-service:8082
      USER_SERVICE_BASEURL: user-service:8083

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

volumes:
  thread-db:
  interaction-db:
  user-mongo:
