spring.application.name: gateway

server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: thread-service
          uri: http://${THREAD_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/threads
            - Method=GET,POST
          filters:
            - SetPath=/api/threads
        - id: thread-service-single
          uri: http://${THREAD_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/threads/{id}
            - Method=GET,PUT,DELETE
          filters:
            - SetPath=/api/threads/{id}
        - id: thread-service-by-user
          uri: http://${THREAD_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/threads/user/{id}
            - Method=GET
          filters:
            - SetPath=/api/threads/user/{id}

        - id: interaction-service-comment
          uri: http://${INTERACTION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/comments
            - Method=POST
          filters:
            - SetPath=/api/comments
        - id: interaction-service-reactions
          uri: http://${INTERACTION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/reactions
            - Method=POST
          filters:
            - SetPath=/api/reactions

        - id: user-service-single
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/users/{id}
            - Method=GET
          filters:
            - SetPath=/api/users/{id}/profile
