### GET all users

GET http://localhost:8083/api/users

### POST a new user

POST http://localhost:8083/api/users

### GET user by ID

GET http://localhost:8083/api/users/675a97999772ed412297be75

### GET user profile by ID

GET http://localhost:8083/api/users/675a97999772ed412297be75/profile
