### GET all threads
GET http://localhost:8081/api/threads

### GET thread with ID 1
GET http://localhost:8081/api/threads/1

### GET threads by user 1
GET http://localhost:8081/api/threads/user/675a97999772ed412297be75

### POST new thread
POST http://localhost:8081/api/threads
Content-Type: application/json

{
  "title": "New Thread",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}

### PUT thread with ID 2
PUT http://localhost:8081/api/threads/2
Content-Type: application/json

{
  "title": "Updated Thread",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
}

### DELETE thread with ID 2
DELETE http://localhost:8081/api/threads/2
